# Generated by Django 4.1.1 on 2022-11-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_max_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_display',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='save_and_hide',
            field=models.BooleanField(default=False),
        ),
    ]
