# Generated by Django 4.1.1 on 2022-11-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_default_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='open_hn_by_default',
            field=models.BooleanField(default=False),
        ),
    ]
