# Generated by Django 4.1.1 on 2022-12-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_open_hn_by_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='open_in_new_tab',
            field=models.BooleanField(default=False),
        ),
    ]
