# Generated by Django 4.1.1 on 2022-12-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_open_in_new_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='startup_page',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
