# Generated by Django 4.1.1 on 2023-01-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_startup_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='max_story',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hightlight_comment_threshold',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hightlight_score_threshold',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='story_per_page',
            field=models.IntegerField(default=25),
        ),
    ]
