# Generated by Django 4.1.1 on 2022-10-15 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1024)),
                ('author', models.CharField(max_length=128)),
                ('score', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('url', models.CharField(max_length=1024)),
                ('descendants', models.IntegerField(default=0)),
                ('is_top', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('is_best', models.BooleanField(default=False)),
                ('is_ask', models.BooleanField(default=False)),
                ('is_show', models.BooleanField(default=False)),
                ('is_job', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved', models.BooleanField(default=False)),
                ('ignored', models.BooleanField(default=False)),
                ('story_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feed.story')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
