# Generated by Django 4.1.1 on 2022-10-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewStory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1024)),
                ('author', models.CharField(max_length=128)),
                ('score', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('url', models.CharField(max_length=1024)),
                ('descendants', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopStory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1024)),
                ('author', models.CharField(max_length=128)),
                ('score', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('url', models.CharField(max_length=1024)),
                ('descendants', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
