# Generated by Django 4.1.1 on 2022-10-15 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstory',
            old_name='story_id',
            new_name='story',
        ),
        migrations.RenameField(
            model_name='userstory',
            old_name='user_id',
            new_name='user',
        ),
    ]
