# Generated by Django 4.1.1 on 2022-10-17 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
